### ISSUE TITLE
Problems about making intermediates in eom-ccsd

### ISSUE THREAD

**Issue by DavidMing-2001** [psi4/psi4numpy#118]
I am an undergraduate from China. Recently I'm read your code in repo psi4/psi4numpy to learn how to implement eom-ccsd method in python.
In the process of reading the code, I noticed that there are some small differences in making intermediates between code for ground state CCSD method and code for eom-ccsd method.
For example, in Stanton's paper, equation(9) is:
![unnamed](https://user-images.githubusercontent.com/54764530/146857851-8ea54965-a2f7-4e73-a9d3-425960463e67.png)
While in the code for ground state CCSD method(in repo psi4/psi4numpy/coupled cluster/spin_orbital/CCSD / CCSD.py), the part is implemented as:
![unnamed](https://user-images.githubusercontent.com/54764530/146857893-129636aa-9eb7-48e1-8784-175e901eaada.png)

However, in the code for eom-ccsd(in repo psi4/psi4numpy/coupled_cluster/RHF/helper_ccenergy.py), this part is implemented as:
![unnamed](https://user-images.githubusercontent.com/54764530/146857907-44bc56a7-ea46-4a1f-ae45-e0e4df3b3ffe.png)

Obviously in the latter case the minus term in the bracket has been neglected.  This kind of  problem happened in making other intermediates as well. However, the weird thing is that one will get very close output using two functions.

**Comment by dgasmith** [comment]
Hello, thank you for noticing this. It does indeed look like a mistake. The `T1` cross terms are often very small for well converged wave functions. Would you mind opening a PR for a fix?

**Comment by ashutoshvt** [comment]
Hi Daniel @dgasmith , the EOM-CCSD code is spin-free while the CCSD code mentioned by @DavidMing-2001 is in spin-orbitals. You can see that in the spin-free case i.e for tau^{alpha, beta}_{alpha, beta}, only the first term would survive!

**Comment by dgasmith** [comment]
Ah, thanks @ashutoshvt! Makes perfect sense, is there a piece of documentation that alludes to this fact?

**Comment by ashutoshvt** [comment]
Actually, we put all the spin-adapted CC helper functions in the RHF folder: `psi4/psi4numpy/coupled_cluster/RHF/`.  Also, in the eom class's docs, we mention it as spin-adapted: 
```
class HelperCCEom(object):
    """
    EOMCCSD helper class for spin adapted EOMCCSD
    """
```

**Comment by DavidMing-2001** [comment]
Sorry, I haven't looked at github for a while, because recently I am preparing for final exam week, Now all of my exams have finished. I am very glad to help to fix this issue, but could you please tell me what is PR?

**Comment by DavidMing-2001** [comment]
I also have a small question about the code, and I don't know whether this is a issue, in stanon's paper,  equation(3) is constructed as:
![image](https://user-images.githubusercontent.com/54764530/148063896-39620b7b-c42e-4f81-91b7-cc19a43bb746.png)
However, in your code, this part is implemented as(in repo psi4/psi4numpy/coupled_cluster/RHF/helper_ccenergy.py):
![image](https://user-images.githubusercontent.com/54764530/148063986-48b44ace-5986-4f3f-b9f5-f21b9418feed.png)
I notice there are coefficients difference and some extra term about exchange two body integral in your code. I am wondering about the reason of making this difference.

**Comment by lothian** [comment]
The difference between the published equation of Stanton and the code above is spin-adaptation.  Stanton's equations are in the spin-orbital basis and thus applicable to a spin-restricted or -unrestricted representation.  The specific code you quote assume a closed-shell reference determinant and a singlet target CC state.

**Comment by DavidMing-2001** [comment]
Oh, thanks for you reply, I notice that there is some difference between the CCSD energy calculated from Spin_orbital_CCSD and RHF. Is this difference also due to spin adaptation?

**Comment by lothian** [comment]
There should be essentially no difference between the spin-orbital and spin-adapted CCSD energies.  Can you be more specific as to the magnitude of the difference you're seeing – perhaps provide an input?

**Comment by lothian** [comment]
Those aren't the same calculation because they use different basis sets.  The EOM-CCSD test case uses the cc-pVDZ basis, and the spin-orbital CCSD test uses the 3-21G basis. 

Also the units on the energies are Hartrees, not eV.

**Comment by DavidMing-2001** [comment]
Oh, I understand, many thanks.
