### ISSUE TITLE
Additional term in making matrix elements of similarily transformed hamiltonian

### ISSUE THREAD

**Issue by DavidGoing** [psi4/psi4numpy#122]
In the code of making matrix elements of similarily transformed hamiltonian(coupled cluster/RHF/helper_cchbar).
![image](https://user-images.githubusercontent.com/54764530/161929354-a6d108fe-36b0-4071-9672-a3189607decc.png)
The notes tell that these term only differ by one sign. 
However, additional term appears in build_Hovvo, making the hamiltonian no longer antisymmetric.
![image](https://user-images.githubusercontent.com/54764530/161929930-953ed557-a05a-4284-ab2c-1c2b86a8c552.png)
I am wondering what happened and why this term is needed.

**Comment by lothian** [comment]
In a spin-adapted RHF formalism, these two terms are distinct.  Antisymmetry of the integrals and HBAR matrix elements only applies in a spin-orbital formulation.
