### ISSUE TITLE
Continuous Integration & testing for PRs

### ISSUE THREAD

**Issue by dsirianni** [psi4/psi4numpy#18]
I think we need some sort of continuous integration testing of pull requests to ensure there are no underlying errors which may break the main repo.  I think this continuous integration should (ideally)

- call the most recent release versions of Psi4 and NumPy, and
- look for `compare_values` and ensure both reference implementations and tutorials pass, 

as well as (possibly) recommending PEP-compliant code style if possible.  I think TravisCI is ideal, since they employ Pytest for Python integration and Psi4 already uses them.  @loriab since the psi4numpy repo is within the Psi4 organization, would we be able to use Psi4's existing Travis account for this purpose?   

For testing the interactive tutorials, we could potentially get Travis to execute 
```
ipython nbconvert --to script tutorial.ipynb
```
which exports `tutorial.ipynb` to `tutorial.py`, before testing `tutorial.py` on the same footing as a reference implementation.  

Thoughts?

**Comment by loriab** [comment]
I need to work on pre-build psi4 on Travis-CI for FAE, so psi4numpy can benefit from that config once in place. I agree pytest is the right framework. What pythons are you supporting? I'd focus on the ref impl as a first step before getting ipython involved. Repos get authorized one-by-one on travis. No problem on the overall psi4 org though.

**Comment by dgasmith** [comment]
Yea now that we can pull a Psi4 1.1 build down we can build around that. For python no reason not to do 2.7/3.5/3.6. If we only have one three im ok with that as well.

Agreed on the iPython side, not entirely sure what that should look like yet.

**Comment by dgasmith** [comment]
I think we have now done this.
