### ISSUE TITLE
Missing documentation inside EOM-CCSD

### ISSUE THREAD

**Issue by jdmcclain47** [psi4/psi4numpy#45]
I was looking at the HelperCCPert object in the file psi4numpy/Coupled-Cluster/spin_free_CC/helper_cc.py.

I was wondering what sort of (perturbative correction?) equations were implemented here.  Could you maybe provide a reference?  Thanks!

**Comment by ashutoshvt** [comment]
I am working on adding the proper references and documentation through https://github.com/psi4/psi4numpy/pull/42. I hope to accomplish this soon.

**Comment by ashutoshvt** [comment]
Fixed via #42.

**Comment by dgasmith** [comment]
@ashutoshvt Can you provide a line link as that PR is quite big?

**Comment by ashutoshvt** [comment]
Please take a look at this for a detailed info on solving CCSD linear response equations. https://github.com/psi4/psi4numpy/blob/master/Response-Theory/Coupled-Cluster/RHF/cc_response.pdf. The equations for perturbed amplitudes are solved [here](https://github.com/psi4/psi4numpy/blob/dc0b51d9a05286023474e1e5b4828705676bf60d/Response-Theory/Coupled-Cluster/RHF/helper_ccpert.py#L191-L257) and [here](https://github.com/psi4/psi4numpy/blob/dc0b51d9a05286023474e1e5b4828705676bf60d/Response-Theory/Coupled-Cluster/RHF/helper_ccpert.py#L423-L482) and the linear response function is constructed [here](https://github.com/psi4/psi4numpy/blob/dc0b51d9a05286023474e1e5b4828705676bf60d/Response-Theory/Coupled-Cluster/RHF/helper_ccpert.py#L596-L635). @jdmcclain47 let me know if this answers your question.

**Comment by jdmcclain47** [comment]
Great! Found everything now; there is just a couple of different defined perturbative approaches for excited states out there so I was confused at first.  The references in the python files clear it up now.
