### ISSUE TITLE
Mint release before publication

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4numpy#46]
In preparation for the final submission of the Psi4NumPy paper we need to mint a final release that can be tagged with Zenodo. I plan to do this Friday, February 23rd. Please submit any desired changes before this deadline.

**Comment by amjames** [comment]
Probably a good time to bring this back on the radar. Since I see the manuscript has officially been submitted as of this afternoon!

**Comment by dgasmith** [comment]
Good point. I looked into the submitted draft and points specifically to the last release rather than the general project on Zenodo. A link to GitHub is here.

I went ahead and minted a pre-release version, hopefully the reviewers will be able to find this new mint (its shown on Zenodo) or the GitHub repo. This is a must-do before final publication. Thanks!

**Comment by dgasmith** [comment]
v1.0 minted and distributed. Thanks for the comment.
