### ISSUE TITLE
Reference Implementation Citations

### ISSUE THREAD

**Issue by dgasmith** [psi4/psi4numpy#9]
Ensure that all reference implementations have correct citations attached.

**Comment by dsirianni** [comment]
I think the most natural method for documenting this is within each method-directory's README, separated into sections for each script in that directory.  So, the README would look something like:

Coupled Cluster Theory
==================

*brief description of contents*

# References
## CCSD.py
1. [J. F. Stanton, *et al.* *J. Chem. Phys.* **94**, 4334 (1991)](http://dx.doi.org/10.1063/1.460620)
2. T. D. Crawford, "The Coupled Cluster Singles and Doubles (CCSD) Energy." Accessed via the web at http://sirius.chem.vt.edu/wiki/doku.php?id=crawdad:programming:project5.

## CCSD_T.py
1. T. D. Crawford, "A Perturbative Triples Correction to CCSD: CCSD(T)." Accessed via the web at http://sirius.chem.vt.edu/wiki/doku.php?id=crawdad:programming:project6.

## TD-CCSD.py
1. [D. R. Nascimento and A. E. DePrince III, *J. Chem. Theory Comput.*, **12**, 5834 (2016)](http://dx.doi.org/10.1021/acs.jctc.6b00796)
2. [J. F. Stanton, *et al.* *J. Chem. Phys.* **94**(6), 1991](http://dx.doi.org/10.1063/1.460620)

Thoughts?

**Comment by loriab** [comment]
I'm a little wary of detaching citations from the home file. But I do like the overview that the README involves.

How about put the main citations in README, let them autonumber, and also include a [LNA:page] or [LNFA:year:page] before the full citation, then in the script itself, refer to the "[LNA:page], Eq. 6". (LNA = first letter of last names of each author in full author list; LNFA = last name of first author)

**Comment by dgasmith** [comment]
Is there any particular reason to move the citations out of the home files? If anything I would think that we would need both. Echoing above, I really like the README to do *something* similar to the SAPT one.

**Comment by dsirianni** [comment]
I definitely agree we need both.  I really like @loriab's proposal that we use the [LNFA:yr:pp] key scheme, so the citations within the scripts are more concise, while unambiguous.

**Comment by dsirianni** [comment]
Thoughts on having the referencing scheme take the following form:

1. `[LNFA:yy:pp]` keys for appropriate references in script headers,
2. `[LNFA:yy:pp] Eqn. 5` in comments nearby code implementing a particular equation, and
3. `References.md` in each method directory or list of references added to README

I agree w/ @dgasmith that each method-dir should have a more verbose README like SAPT, but I have no opinion one way or the other about references in the README or in a separate file.

**Comment by dgasmith** [comment]
References should go in the reference implementations IMO. The above is fine, but should nuke Reference.md IMO. If you want to a list or link to the references used in the reference implementations we can add it to the end of the README.

**Comment by amjames** [comment]
Just wanted to point out that the crawford group programing projects have moved to [github](https://github.com/CrawfordGroup/ProgrammingProjects/tree/master/Project%2305), so any links should probably point there since the old group wiki may not be online for much longer. The content is the same for the most part. I do plan to update some of the psi4 plugin based stuff though.

**Comment by dsirianni** [comment]
Assigning myself to this issue to go through and bring all ref implementations up-to-date w/ new contributor guidelines.

**Comment by dgasmith** [comment]
@dsirianni Can you do a pass over this over the next several days?

**Comment by dsirianni** [comment]
Will do ASAP.  Sorry, I was away from internet for a few days doing wedding-planning stuff.
